### PR TITLE
Best Practices and Clean-Up

### PR DESCRIPTION
**Pull request by jameskbride**
@jessharrell , I made some changes here to get this skeleton in line with some of the Java standards and made sure it was using the latest and greatest version of JUnit.  Let me know what you think and if things are good please merge my pull request.  Thanks.

### CODE REVIEW

**Comment by jessharrell** [comment]
@jameskbride Thanks for the help. While on the bench, I've been tasked with creating a bunch of these skeletons. My level of confidence in these languages vary, and I appreciate those with more experience helping improve our skeletons.

**Comment by jameskbride** [comment]
No worries, glad to help!

**Comment by shieldscr** [comment]
Why not Java 8 and Gradle?

**Comment by mcibulskis** [comment]
You beat me to the same question :)

**Comment by jameskbride** [comment]
I had that thought initially as well.  I didn't go that far because Java 8 is still not as widely distributed as Java 7, same thing for Gradle.  Maven comes installed on a Mac out of the box, and can be easily installed on other OSs. Yes, I know this is true for Java 8 and Gradle as well.  I was essentially going for the lowest common denominator for SDKs and build tools.  

Thoughts?

**Comment by mholtman** [comment]
Two skeletons, one for 7 and one for 8?

**Comment by mcibulskis** [comment]
So, what are the intended use cases for these skeletons?  What value are they providing and to whom?

**Comment by mholtman** [comment]
Personally, I can see two. One, internal use to get people up and running quickly. Two, tell a potential candidate to use the skeleton to do their kata.

**Comment by udioeater** [comment]
I would have found it useful a couple of weeks ago if we had had some kind of java/selenium/cucumber skeleton project to help my team get started with it... I dunno if that counts as a separate thing from Mark's first use case, but it is a real life example. :)

**Comment by kvnknowles** [comment]
One other benefit is to get some more internal collaboration on non-client work.  I had heard people bring up having more things out on Pillar's github that could be leveraged when walking in to a project.  To steal @jameskbride's (I think) comment, build up a toolbox that any Pillarite could use.

**Comment by mcibulskis** [comment]
I'd rather see a candidate do this on their own for a kata or pairing interview. It can be telling if they have no clue how to start and can't do the research (or be bothered) to figure it out.  After that has been observed, the skeleton would be useful to see what else they can do.

I agree the other use case for Pillarites to quick start an effort would be useful.

With those use cases in mind, does it still make sense to have older versions of languages for the skeletons?

**Comment by npresto** [comment]
I can't agree with @mcibulskis more. When I did my katas I was came in with little experience outside of the .NET world, where setting up a dev environment is infinitely more simplistic than standing up a Java or C++ environment. A decent chunk of time was spent just getting over these hurdles, and as Mike said, the motivation(or lack of) can paint a pretty clear picture into a candidate.    

Hopefully we haven't hijacked this thread beyond recovery.

**Comment by jameskbride** [comment]
I think this has been a good discussion.  That being said, let me tell you leave you with an anecdote that occurred less than five minutes ago.  My wife asked me for a Phillips screwdriver to repair something (she says "star" no matter how many times I tell her it's a Phillips, but anyway...).  The need being made apparent I reached into my toolbox, pulled out the requested tool and passed it to my daughter for my wife's use.  Actually, to be specific I pulled out a multi-bit screwdriver with the bits just in case she actually, really needed a "star" and not a Phillips.  I was able to do this because I had the tool in my toolbox.

My point here is that it's better to have the tool and not need it, versus not having the tool because "we're not sure what value there is in having the tool".  

I agree with the points about wanting to see what a candidate is bringing to the table.  If you'd like to do that then by all means, don't use the screwdriver.  We're all craftspeople here, and we can make the on-to-spot decision as to whether or not we need that tool for a particular project.  On the other hand, if we do need the screwdriver I'd like to have it on hand "just in case", and you know, it would be nice if other bits were there in case I needed a "star" vs a phillips.  

On that note I see someone has already kindly taken the time to create a Java 8 Gradle skeleton as well.  Now we have both tools in our toolbox.

**Pull request merged**
